version: '2'
services:
    rabbit:
        image: rabbitmq:3.5.1-management
        ports:
            - "5672:5672"
    sat-master:
        image: aereg/minicloud-server
        volumes:
            - ../logs:/root/logs
        network_mode: "host"
        command: >
          sh -c "sleep 5;
                 touch server.jar;
                 java -jar \
                      -Dspring.profiles.active=localDocker \
                      -Djava.security.egd=file:/dev/./urandom server.jar"