version: '2'
services:
    rabbit:
        image: rabbitmq:3.5.1-management
        ports:
            - "5672:5672"
    sat-master:
        image: aereg/minicloud-server
        volumes:
            - ../logs:/root/logs
        network_mode: "host"
        command: sh -c "sleep 5; touch server.jar; java -jar -Dspring.profiles.active=local -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 server.jar"